#
# Basic Build Setup
#

dist: bionic
language: c
before_install:
        - sudo apt-get -qqy update && sudo apt-get install libdvbcsa-dev dvb-apps libssl-dev -qqy
script:
  - ./configure
  - make -j 4
  - make test

