name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    container: catalinii/minisatip-build-image:latest
    steps:
    - uses: actions/checkout@v2
      - name: Configure ARM
        run: |
         ./configure --enable-enigma --enable-staging --host=arm-linux-gnueabihf
         make

