name: Binaries
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    container: catalinii/minisatip-build-image:latest
    steps:
    - uses: actions/checkout@v2
    - name: Configure ARM
      run: |
       ./configure --enable-enigma --enable-static --host=arm-linux-gnueabihf --disable-dvbaes --disable-dvbca
       make

