name: Coverity

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  coverity:
    runs-on: ubuntu-latest
    steps:
      - name: Install libraries
        run: |
          set -x
          sudo apt-get update
          sudo apt-get install libssl-dev dvb-apps libdvbcsa-dev

      - name: Download Coverity Build Tool
        run: |
          wget -q https://scan.coverity.com/download/cxx/linux64 --post-data "token=$TOKEN&project=MINISATIP" -O cov-analysis-linux64.tar.gz
          mkdir cov-analysis-linux64
          tar xzf cov-analysis-linux64.tar.gz --strip 1 -C cov-analysis-linux64
        env:
          TOKEN: ${{ secrets.COVERITY_SCAN_TOKEN }}

      - name: Fixed world writable dirs
        run: |
          chmod go-w $HOME
          sudo chmod -R go-w /usr/share

      - name: Configure
        run: ./configure

      - name: Build with cov-build
        run: |
          export PATH=`pwd`/cov-analysis-linux64/bin:$PATH
          cov-build --dir cov-int make

      - name: Submit the result to Coverity Scan
        run: |
          tar czvf MINISATIP.tgz cov-int
          curl \
            --form project=MINISATIP \
            --form token=$TOKEN \
            --form email=t_cata_2000@yahoo.com \
            --form file=@MINISATIP.tgz \
            --form version=trunk \
            --form description="`./minisatip -v`" \
            https://scan.coverity.com/builds?project=MINISATIP
        env:
          TOKEN: ${{ secrets.COVERITY_SCAN_TOKEN }}
